name: hello Github

on:
  # push:
  #   branches: [main]
  #   paths: ['*/*/CICD.yml']

  workflow_dispatch:
      inputs:
        enviroment:
          description: "choose ENV"
          default: 'dev'
          required: true
          type: choice
          options:
            - dev
            - prod
            - staging


jobs:
  code:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        run: echo "code clone from github"

  buid:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: build the code
        run: echo "build the code using docker"

  test:
    needs: buid
    runs-on: ubuntu-latest
    steps:
      - name: test the code
        run: echo "test the code using testing tools"

  dipatch:
    if: inputs.enviroment== 'dev'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: dispatch the cluster on server
        run: echo "disptach the code on server "
